### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by aaesth** [unsmxrt/kinggen-java#1]
keeps saying java: finished parsing for some reason please fix or millie bobby brown will be alerted 💅

**Comment by DxsSucuk** [comment]
Unsure if this repo is still being maintained, but if not you could use this one [here](https://github.com/DxsSucuk/KingGenJava)

**Comment by unsmxrt** [comment]
> Unsure if this repo is still being maintained, but if not you could use this one [here](https://github.com/DxsSucuk/KingGenJava)

he isnt serious 🤯
and yes my repository is maintained, there is just nothing new to add. does the job perfectly

**Comment by levzzz5154** [comment]
Cvm

**Comment by unsmxrt** [comment]
would be lovely if you stated that you took inspiration from my code in your repository's readme 🥰🥰

> you could use this one [here](https://github.com/DxsSucuk/KingGenJava)

**Comment by levzzz5154** [comment]
![image](https://user-images.githubusercontent.com/86072227/178808941-c56eaf93-284b-4608-95d0-2e056f30f2dc.png)

**Comment by DxsSucuk** [comment]
> would be lovely if you stated that you took inspiration from my code in your repository's readme 🥰🥰
> 
> > you could use this one [here](https://github.com/DxsSucuk/KingGenJava)

👍
